version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run: yarn build

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: org-global
